apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-operator
  namespace: deploy-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: deploy-operator
    spec:
      serviceAccountName: deploy-operator
      containers:
      - name: deploy-operator
        image: xxx/cicd/canary-deploy-controller:v0.1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
